apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-post-install"
  labels:        
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "5"
data:
  VERSION: {{ .Chart.Version | quote }}
